import React from 'react';
import { useAuth } from './AuthProvider';
import { Button } from './ui/button';
import { Brain, Sparkles, GraduationCap, ArrowRight } from 'lucide-react';
import { motion } from 'motion/react';

export const Landing: React.FC = () => {
  const { login } = useAuth();

  return (
    <div className="flex flex-col items-center justify-center pt-20 pb-20 px-6 min-h-screen bg-indigo-50">
      <motion.div 
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl text-center"
      >
        <div className="mx-auto mb-8 flex h-20 w-20 items-center justify-center rounded-[2rem] bg-indigo-600 text-white shadow-2xl shadow-indigo-200">
          <Brain className="h-10 w-10" />
        </div>
        <h1 className="mb-6 text-5xl font-black tracking-tighter text-indigo-950 md:text-8xl italic uppercase">
          PathWise <span className="text-indigo-600 drop-shadow-sm">AI</span>
        </h1>
        <p className="mb-12 text-xl text-slate-500 font-medium md:px-20 leading-relaxed">
          Stop following random tutorials. Get a personalized, adaptive learning path generated by AI 
          that understands your goals, time, and pace.
        </p>
        
        <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
          <Button size="lg" className="h-16 px-10 text-lg font-black uppercase tracking-widest bg-indigo-600 rounded-2xl shadow-2xl shadow-indigo-200 hover:scale-105 transition-all" onClick={login}>
            Initialize Mission <ArrowRight className="ml-2 h-6 w-6" />
          </Button>
          <Button variant="outline" size="lg" className="h-16 px-10 text-lg font-black uppercase tracking-widest rounded-2xl border-indigo-200 text-indigo-600 bg-white">
            Architecture
          </Button>
        </div>
      </motion.div>

      <div className="mt-32 grid grid-cols-1 gap-8 md:grid-cols-3 md:max-w-6xl">
        <FeatureCard 
          icon={<Sparkles className="h-6 w-6 text-indigo-600 font-black" />}
          title="Adaptive Roadmap"
          description="Your path adjusts automatically if you struggle or speed ahead. Real-time path recalibration."
        />
        <FeatureCard 
          icon={<GraduationCap className="h-6 w-6 text-indigo-600" />}
          title="Quest Planner"
          description="Clear daily quests derived from your roadmap to keep you in the state of flow."
        />
        <FeatureCard 
          icon={<Brain className="h-6 w-6 text-indigo-600" />}
          title="Oracle Mentor"
          description="An always-on deep-explainer to guide you through complex technical roadblocks."
        />
      </div>
    </div>
  );
};

const FeatureCard = ({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) => (
  <motion.div 
    whileHover={{ y: -10, scale: 1.02 }}
    className="rounded-[2.5rem] border border-indigo-100 bg-white p-10 shadow-sm transition-all hover:shadow-2xl hover:shadow-indigo-100 group"
  >
    <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-50 group-hover:bg-indigo-600 group-hover:text-white transition-colors duration-500">
      {icon}
    </div>
    <h3 className="mb-3 text-2xl font-black text-indigo-950 tracking-tight uppercase tracking-tighter">{title}</h3>
    <p className="text-slate-500 font-medium leading-relaxed">{description}</p>
  </motion.div>
);
